server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Livraria
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: pessoa-service
  output:
    ansi:
      enabled: always